guidance/branches/urls.py
from django.conf.urls import url
from . import views

app_name='branches'

urlpatterns = [
    # /branches/
    url(r'^$',views.index,name='index'),

	# /branches/66
	url(r'^(?P<departments_id>[0-9]+)/$', views.detail, name='detail' ),

   # /branches/66/favorite
   url(r'^(?P<departments_id>[0-9]+)/favorite/$', views.favorite, name='favorite' ),
 ]

guidance/guidance/urls.py

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
   
    url(r'^admin/', admin.site.urls),
    url(r'^branches/', include('branches.urls')),

]

guidance/branches/models.py
from django.db import models

class Departments(models.Model):
  department_name=models.CharField(max_length=400)
  deptartment_information=models.CharField(max_length=5000)
  department_coresubject=models.CharField(max_length=1000)
  department_logo=models.CharField(max_length=1000)


  def __str__(self):
   return self.department_name + ' - ' +self.department_coresubject

class companies(models.Model):
  departments = models.ForeignKey(Departments, on_delete=models.CASCADE)
  company_name=models.CharField(max_length=2000)
  company_turnover=models.CharField(max_length=300)
  is_favorite = models.BooleanField(default=False)


  def __str__(self):
   return self.company_name 

class college(models.Model):
  departments = models.ForeignKey(Departments, on_delete=models.CASCADE)
  college_name= models.CharField(max_length=300)
  college_intake=models.CharField(max_length=300)
  college_logo=models.CharField(max_length=1000)








guidance/branches/views.py
from django.shortcuts import render,get_object_or_404
from .models import Departments,companies



def index(request):
  all_departments = Departments.objects.all()
  return render(request, 'branches/index.html', {'all_departments':all_departments})

def detail(request, departments_id):
 departments = get_object_or_404(Departments, pk=departments_id)
 return render(request, 'branches/detail.html', {'departments':departments})


def favorite(request, departments_id):
  departments = get_object_or_404(Departments, pk=departments_id)
  try:
	   selected_companies = departments.companies_set.get(pk=request.POST['companies'])
  except (KeyError, companies.DoesNotExist):
	    return render(request, 'branches/detail.html' , {
		       'departments':departments,
		       'error_message': "you did not select a valid song",
			   'companies':companies,
		})
  else:
   selected_companies.is_favorite = True
   selected_companies.save()
   return render(request, 'branches/detail.html', {'departments':departments})


guidance/branches/templates/branches/detail.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<style>

img.logo{
	width:50%;
	border-radius:50%
}











</style>
</head>

<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light" >
<a class="navbar-brand" href="#" style="max-width:5%;max-height: 5%">
    <img src="https://www.the-work-guide.com/gallery/decision-making-techniques/decision_making_techniques.jpg" class="img-fluid">
 </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">HOME<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">ABOUT</a>
      </li>
     <li class="nav-item">
        <a class="nav-link" href="#">CONTACT US</a>
        </li>
         <li class="nav-item">
        <a class="nav-link" href="#">FAQ's</a>
        </li>
        </ul>
          </div>
      </nav>
	  <div class="container">
	  <div class="row">
	      <div class="col-lg-6">

<img src="{{ departments.department_logo}}">
</div>
    <div class="col-lg-6">


<h1><center><b>{{ departments.department_name }}</b></center></h1>
<p1>{{ departments.deptartment_information }}</p1>
<h2><center>CORE SUBJECTS</center></h2>
<h3>{{departments.department_coresubject}}</h3>
</div>
</div>
</div>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}


<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

guidance/branches/templates/branches/index.html
{% if all_departments %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light" >
<a class="navbar-brand" href="#" style="max-width:5%;max-height: 5%">
    <img src="https://www.the-work-guide.com/gallery/decision-making-techniques/decision_making_techniques.jpg" class="img-fluid">
 </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">HOME<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">ABOUT</a>
      </li>
     <li class="nav-item">
        <a class="nav-link" href="#">CONTACT US</a>
        </li>
         <li class="nav-item">
        <a class="nav-link" href="#">FAQ's</a>
        </li>
        </ul>
          </div>
      </nav>
       <h1 style="text-align: center;padding: 5px;font-size: 30px;font-family: serif;color: cadetblue"><strong>LIST OF DEPARTMENTS!</strong></h1>
      <div class="row">
	  <div class="column">
       <img src="https://files.askiitians.com/cdn1/images/2014630-182329784-9122-br.jpg" alt="branches">
	   </div>
	   <div class="column">
  <ul>
    {% for departments in all_departments %}
    <li><a href="{% url 'branches:detail' departments.id %}">{{ departments.department_name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
   <h3>You dont have any departments</h3>
{% endif %}


<img src="https://vowofpracticality.com/wp-content/uploads/2017/04/QuestionConfusedMan.png" alt="thinking" width=200 height=200>
</div>
</div>
<h2><b><u>Engineering</u></b></h2>
<p> Engineering is the application of knowledge in the form of science, mathematics, and empirical evidence, to the innovation, design, construction, operation and maintenance of structures, machines, materials, software, devices, systems, processes, and organizations. The discipline of engineering encompasses a broad range of more specialized fields of engineering, each with a more specific emphasis on particular areas of applied mathematics, applied science, and types of application. See glossary of engineering.</p>
</body>